# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: windows-latest

variables:
- group: graduateCase_Variables

  

steps:
- script: dotnet build --configuration Release
  displayName: 'dotnet build Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Jens Struckmann(203576a1-6dee-472b-861d-016b6ed517c2)'
    appType: 'webAppLinux'
    appName: 'graduatecaseApp'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'


- task: AzureMysqlDeployment@1
  inputs:
    azureSubscription: 'Jens Struckmann(203576a1-6dee-472b-861d-016b6ed517c2)'
    ServerName: '$(MySQLServer-Name).mysql.database.azure.com'
    SqlUsername: '$(MySQLServer-Username)@$(MySQLServer-Name)'
    SqlPassword: '$(MySQLServer-Password)'
    TaskNameSelector: 'InlineSqlTask'
    SqlInline: |
      DROP DATABASE IF EXISTS quickstartdb;
      CREATE DATABASE quickstartdb;
      USE quickstartdb;
      
      -- Create a table and insert rows
      DROP TABLE IF EXISTS inventory;
      CREATE TABLE inventory (id serial PRIMARY KEY, name VARCHAR(50), quantity INTEGER);
      INSERT INTO inventory (name, quantity) VALUES ('banana', 150);
      INSERT INTO inventory (name, quantity) VALUES ('orange', 154);
      INSERT INTO inventory (name, quantity) VALUES ('apple', 100);
      
      -- Read
      SELECT * FROM inventory;
      
      -- Update
      UPDATE inventory SET quantity = 200 WHERE id = 1;
      SELECT * FROM inventory;
      
      -- Delete
      DELETE FROM inventory WHERE id = 2;
      SELECT * FROM inventory;
    IpDetectionMethod: 'AutoDetect'